server:
  port: 8888

spring:

  jpa:
    database-platform:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate: info
      springframework:
        security: debug
